### PR TITLE
Added Pull Request Guidelines Documentation

### PR DESCRIPTION
**Pull request by robguy21**
## Proposed changes

This PR adds PR Guidelines (more like principles I guess) to be followed by authors and reviewers alike.

Loosely based on an [excellent thread](https://twitter.com/TejasKumar_/status/1129056162656260096) by [@TejasTumar_](https://twitter.com/TejasKumar_/)

### CODE REVIEW

**Comment by sscholle** [comment]
might be useful to warn about common PR pitfalls using DANGER tool: https://danger.systems/js/

**Comment by robguy21** [comment]
> might be useful to warn about common PR pitfalls using DANGER tool: https://danger.systems/js/

Added issue for this

**Comment by robguy21** [comment]
> I appreciate all the effort and thought that has gone into this. I do feel the legibility can be improved by using some `preformatted` `styling`.
> 
> I'll checkout your fork and make some changes to the formatting of it

Go for it- it's probably a better idea if you checkout the fork and implement the visual changes. I'm not too sure where/how to implement what you're suggesting 👍

**Comment by sscholle** [comment]
@robguy21 i have a repo with some info regarding `commit messages` here: https://github.com/sscholle/best_practices perhaps we can add an issue/pr with some of that?

**Comment by robguy21** [comment]
> @robguy21 i have a repo with some info regarding `commit messages` here: https://github.com/sscholle/best_practices perhaps we can add an issue/pr with some of that?

I think that's outside the scope of this PR but you can go ahead and open an issue to include a best practices 👍

**Pull request merged**
